apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-deployment
  labels:
    app: bind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind
  template:
    metadata:
      labels:
        app: bind
    spec:
      containers:
      - name: bind
        image: cytopia/bind
        env:
        - name: DOCKER_LOGS
          value: "1" # Enclose numeric value in quotes to ensure it's interpreted as a string
        - name: ALLOW_QUERY
          value: "any" # Enclose string value in quotes
        ports:
        - containerPort: 53
