apiVersion: apps/v1
kind: Deployment
metadata:
  name: sniproxy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sniproxy
  template:
    metadata:
      labels:
        app: sniproxy
    spec:
      hostNetwork: true
      containers:
      - name: sniproxy
        image: ghcr.io/mosajjal/sniproxy:latest
        imagePullPolicy: Always
        args: ["--config", "/tmp/config.yaml"]
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 53
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: "/tmp/config.yaml"
          subPath: "config.yaml"
      volumes:
      - name: config-volume
        configMap:
          name: sniproxy-config
