apiVersion: v1
kind: Service
metadata:
  name: sniproxy-service
spec:
  externalIPs:
  - 192.142.103.24
  type: LoadBalancer
  selector:
    app: sniproxy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53
